import { MessageStateEnum } from '../dashboard-types';
import { MessagesType, MessagesTypesEnum } from './messaging-types';

export const messageInitial: MessagesType[] = [
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Los mensajes son cifrados de extremo a extremo.',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NOTIFICATION,
    isNewDay: false,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
];

export const messagesMockup: MessagesType[] = [
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id mauris, risus id urna tellus velit amet nulla ornare. Varius cras orci euismod malesuada ullamcorper. ',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NOTIFICATION,
    isNewDay: false,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsun dolor',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: true,
    isEdit: true,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsun dolor',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.DOCUMENT,
    isNewDay: false,
    isEdit: false,
    url: '',
    fileName: 'INSTITUTO DE EDUCACIÓN SUPERIOR TECNOLOGICA PUBLICO.docs',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsun dolor, Lorem ipsun dolor. Lorem ipsun dolorLorem ipsun dolor',
    createdAt: 1696688883349,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: true,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsun dolor',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsun dolor',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsun dolor',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsun dolor',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsun dolor',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsun dolor',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: true,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsun dolor',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsun dolor',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Lorem ipsun dolor',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: 'Se unió Johann Meza',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.INFO,
    isNewDay: false,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
  {
    idContactMessage: 0,
    name: 'string',
    message: '',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.LOCKED,
    isNewDay: true,
    isEdit: false,
    url: '',
    fileName: '',
    typeFile: 'doc',
    batchMessage: '',
    idTypeComunication: 0,
    sendDateTime: '',
    idContactMessageState: 0
  },
];
