import { MessageStateEnum } from '../dashboard-types';
import { MessagesType, MessagesTypesEnum } from './messaging-types';

export const messagesMockup: MessagesType[] = [
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id mauris, risus id urna tellus velit amet nulla ornare. Varius cras orci euismod malesuada ullamcorper. ',
    sendId: '1',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NOTIFICATION,
    isNewDay: false,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsun dolor',
    sendId: '1',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.UNREAD,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: true,
    isEdit: true
  },
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsun dolor',
    sendId: '1',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsun dolor, Lorem ipsun dolor. Lorem ipsun dolorLorem ipsun dolor',
    sendId: '2',
    receivedId: '15',
    createdAt: 1696688883349,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: true,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsun dolor',
    sendId: '1',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsun dolor',
    sendId: '1',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsun dolor',
    sendId: '1',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsun dolor',
    sendId: '1',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsun dolor',
    sendId: '1',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsun dolor',
    sendId: '1',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: true,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsun dolor',
    sendId: '2',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsun dolor',
    sendId: '2',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: 'Lorem ipsun dolor',
    sendId: '2',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.NORMAL,
    isNewDay: false,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: 'Se unió Johann Meza',
    sendId: '2',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.INFO,
    isNewDay: false,
    isEdit: false
  },
  {
    id: 'string',
    name: 'string',
    message: '',
    sendId: '2',
    receivedId: '15',
    createdAt: 1696698883341,
    state: MessageStateEnum.READED,
    typeMessage: MessagesTypesEnum.LOCKED,
    isNewDay: true,
    isEdit: false
  },
];